### ISSUE TITLE
Is Python 3 support planned?

### ISSUE THREAD

**Issue by cederom** [threat9/routersploit#162]
Hello! Is Python 3 support planned? I was also using Python 2.7 (as default in FreeBSD and OSX) but Python 3.6 was released recently and myself I consider to switch to Python 3. Do you plan to switch to Python 3 in near future?

**Comment by TiberiumPY** [comment]
You can use many Python version at the same time on your machine

**Comment by cederom** [comment]
Yea @TiberiumPY :-) What I am asking is if RouterSploit going to change to Python3 as default interpreter.. as now its using Python27 and its packages and all (dis)advantages.. :-)

**Comment by lucyoa** [comment]
@cederom The vast majority of security community still uses Python 2.7 so we are not going to switch entire project to Python 3. That's being said it would be cool to make project a Python 3 compatible.

**Comment by fwkz** [comment]
Thanks to @DePierre and  https://github.com/reverse-shell/routersploit/pull/165 we start process of porting RSF to Python 3!

In order to make this common effort we have created `py3` branch so everyone can participate in that process and help with testing and fixing bugs. 

As we don't have every vulnerable device, most critical part of porting is testing already implemented exploits placed in the `modules/` directory. So if anyone is "happy" owner of vulnerable device we would be more than grateful if you can help!

**Comment by lucyoa** [comment]
We switched to Python3
