### ISSUE TITLE
Add CVE-2014-9510

### ISSUE THREAD

**Issue by HerendraTJ** [threat9/routersploit#295]
Add new exploit plz

**Comment by 0BuRner** [comment]
Hi dude !

If you want to add a custom exploit manually, simply add it in **/routersploit/modules/exploits/cameras|misc|routers/** directory and then you can use it.

The best way to have the exploits you want in routersploit is by contributing to the project. The guidelines are here https://github.com/reverse-shell/routersploit/wiki/Contribution-Guidelines

Concerning the exploit you want, it will probably not be added in routersploit because it's a CSRF exploit. You have to create it yourself if you want it.

**Comment by lucyoa** [comment]
For now we are passing on CSRF vulnerabilities.
