### ISSUE TITLE
creds/generic/telnet_default.py crashed with FPT GPON

### ISSUE THREAD

**Issue by trungnv08** [threat9/routersploit#601]
target: 

Device Name : G-97RG3
Hardware Version : C30-401
Software Version : R4.2.43.078g

command: ``` use scanners/autopwn```
Exception thrown: 
``` Python3
Exception in thread thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/routersploit/routersploit/modules/creds/generic/telnet_default.py", line 53, in target_function
    username, password = data.next().split(":")
ValueError: too many values to unpack (expected 2)
```

**Comment by Stewart86** [comment]
I have a similar exception but with 
    /routersploit/routersploit/modules/creds/generic/ssh_default.py

I have checked that the problem lies in one or some of the wordlists txt files.

Some options I can suggest for the fix:
- change `data.next().split(":")` to `data.next().split(":", 1)` (so that it will only find the first `:` and ignore the rest)
- write a test to check all wordlists for extra `:` in a set of username:password key value pair.
