### ISSUE TITLE
Segmentacion Fault | Kali linux

### ISSUE THREAD

**Issue by facudj020** [threat9/routersploit#622]
| |_/ /___  _   _| |_ ___ _ __\ `--. _ __ | | ___  _| |_
 |    // _ \| | | | __/ _ \ '__|`--. \ '_ \| |/ _ \| | __|
 | |\ \ (_) | |_| | ||  __/ |  /\__/ / |_) | | (_) | | |_
 \_| \_\___/ \__,_|\__\___|_|  \____/| .__/|_|\___/|_|\__|
                                     | |
       Exploitation Framework for    |_|    by Threat9
            Embedded Devices

 Codename   : I Knew You Were Trouble
 Version    : 3.3.0
 Homepage   : https://www.threat9.com - @threatnine
 Join Slack : https://www.threat9.com/slack

 Join Threat9 Beta Program - https://www.threat9.com

 Exploits: 128 Scanners: 4 Creds: 165 Generic: 4 Payloads: 32 Encoders: 6

rsf > use scanners/autopwn
rsf (AutoPwn) > set target 192.168.1.1
[+] target => 192.168.1.1
rsf (AutoPwn) > run
[*] Running module...

[*] Starting vulnerablity check...
Segmentation fault
facu@kali:~/Downloads/routersploit-3.3.0$

**Comment by McDonaldsTriad** [comment]
I'm wondering if you actually even read the issues section of routersploit here on GitHub, because if you did you would have seen that the person before you (that's me) had the exact same issue. I closed it because it has now been solved, I ran apt-update followed by apt-upgrade, which fixed the issue.

It would have been useful if you actually had posted the necesary information which is required by GitHub when posting about issues; what kind of OS you're running, which kernel, etcetera. Without that info no one can help you. So I suggest trying out apt-update followed by apt-upgrade (assuming you're running Linux), if that doesn't fix the problem, look around in the issues section and you'll see that there's a whole list of things you were supposed to fill in so people know what system you're running and are more suited to help you.
