### ISSUE TITLE
can some one help me?

### ISSUE THREAD

**Issue by v370r** [threat9/routersploit#696]
can someone help me why cant i set port ?

rsf (AutoPwn) > set target 192.168.0.1
[+] target => 192.168.0.1
rsf (AutoPwn) > set port 80
[-] You can't set option 'port'.
Available options: ['target', 'vendor', 'check_exploits', 'check_creds', 'http_use', 'http_port', 'http_ssl', 'ftp_use', 'ftp_port', 'ftp_ssl', 'ssh_use', 'ssh_port', 'telnet_use', 'telnet_port', 'snmp_use', 'snmp_community', 'snmp_port', 'tcp_use', 'udp_use', 'threads']

hoping for a response!
thanks in advance!

![image](https://user-images.githubusercontent.com/50656923/87814730-47fe7580-c832-11ea-8728-86c4afbf408c.png)

**Comment by pulquiqui** [comment]
friend this is very easy you are wrong "set port" cannot be used in scanners / autopwn the correct thing is "set http_port 80"
![87814730-47fe7580-c832-11ea-8728-86c4afbf408c~2](https://user-images.githubusercontent.com/67844118/87866959-9b191b00-c94d-11ea-8d40-3e78ae2f85aa.png)
even so it is not necessary to assign the port since it is the one that is by default you can check it with the command "show advanced" after assigning the "ip" and look for the value "http_port" and it will be 80 if not, so assign it with  the aforementioned command "set http_port 80"
