### ISSUE TITLE
ISSUE WITH AUTOPWN 

### ISSUE THREAD

**Issue by alvin-tosh** [threat9/routersploit#779]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1. Scan the target
2. search and select autopwn
3. run autopwn against target
4. Error! :worried:

## Your Environment
* RouterSploit Version used: 3.4.0
* Operating System and version: Kali Linux (Virtualbox)
* Python Version: ( `python3 --3.10` )
* Python Environment: ( `python3 -m pip3 freeze` )

## Current Behavior
* After running autopwn against a target ==> Returns an error with 'crypto' AND DOESNT EVER RUN.
* All other modules seem to work fine (the once i have tried) so far.
* # PS: I have tried this on four different kali-linux machines (VIRTUALBOX), updated, uninstalled and installed afresh multiple times and i havent been able to run autopwn at all. :sob:

## Expected Behavior
The module should run and attempt to pwn a router(my router) or show if any vulnerabilities can be exploited by the module

It should Not throw an error.

**Comment by lucyoa** [comment]
Try:
```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
./rsf.py
```

**Comment by AkechiShiro** [comment]
@alvin-tosh you have not provided any command output/information needed in order to understand what is wrong with your environment, so it's hard to know what is wrong.

Mind this line at the top of the issue : 
> ! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

As well as, the commands in \`\` are to be run and their output must be pasted in the issue to help anyone fix your issue, especially `python 3 -m pip3 freeze`, that would show if any package such as `crypto` or any related crypto package is missing, that would explain your issue.
 
> ## Your Environment
> * RouterSploit Version used: 3.4.0
> * Operating System and version: Kali Linux (Virtualbox)
> * Python Version: ( `python3 --3.10` )
> * Python Environment: ( `python3 -m pip3 freeze` )

**Comment by coolst3r** [comment]
https://github.com/threat9/routersploit/issues/808

**Comment by coolst3r** [comment]
> #808

try this

**Comment by alvin-tosh** [comment]
Thank you

**Comment by coolst3r** [comment]
> Thank you

no problem

**Comment by adyzbyte** [comment]
For me this worked:
     
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome
